### ISSUE TITLE
Fails without explanation

### ISSUE THREAD

**Issue by steve-taylor** [onury/grunt-jasmine-nodejs#19] opened 2015-07-06 09:42 UTC
I have this in my Gruntfile:

	test: {
		options: {
			specNameSuffix: '-test.js',
			useHelpers: false,
			stopOnFailure: false,
			reporters: {
				console: {
					colors: true,
					cleanStack: 1,
					verbosity: 4,
					listStyle: 'indent',
					activity: false
				}
			}
		},
		dev: {
			specs: ['tests/**']
		}
	}

When I run `grunt test`, all I get is this:

    Warning: Task "test" failed. Use --force to continue.
    
    Aborted due to warnings.

There is no reason given for the failure, so I have no way of knowing what I need to do to get this working.

I'm using
* node.js 0.12.4
* grunt-cli 0.1.13
* grunt 0.4.5

**Comment by onury** [comment] 2016-02-25 23:58
I think this is rather related with jasmine-core or grunt (if the cause is an `uncaughtException`). Can you try to run the tests with `grunt --stack` command. This will output the stack trace if this is a fatal error. Pls also see [Issue #31](https://github.com/onury/grunt-jasmine-nodejs/issues/31).

**Comment by onury** [comment] 2016-02-27 20:20
I believe this is resolved with the new version (1.5.0)
Closing this. Pls re-open if needed.

**Closed by onury** 2016-02-27 20:20 UTC
Labels: waiting on user
